### ISSUE TITLE
handle raw image to color image

### ISSUE THREAD

**Issue by knmcguire** [bitcraze/AIdeck_examples#15]
- [x] Write a simple demosaicking algorithm

- [x] Stream the color image instead of raw

**Comment by knmcguire** [comment]
quite a lot of articfacts still in the image. Need a more sophisticated demosaicking algorithm

**Comment by noahzn** [comment]
Hi, could you give an example to stream the color image instead of the raw image? Thanks.

**Comment by knmcguire** [comment]
Hi, we don't have this functionality/example yet, and also since the Aideck 1.1 has switched to a grayscale camera it's not our immediate priority. So let me discuss with the team if this is something that we will provide in the coming weeks.

**Comment by noahzn** [comment]
Hi, thanks for your reply.
We try to solve this problem but meet some problems. 
https://forum.bitcraze.io/viewtopic.php?t=5150

**Comment by aqqz** [comment]
Hello, I have a question, why the color of the output rgb image is so green, can I adjust it？

**Comment by knmcguire** [comment]
an update here: please check out this readme to get the color image demosaicking on the computer example https://github.com/bitcraze/AIdeck_examples/tree/cf-link/GAP8/test_functionalities/wifi_jpeg_streamer

It's still a bit messy but we hope to clean it out for the next couple of days.
