### ISSUE TITLE
ai deck

### ISSUE THREAD

**Issue by 4perros** [bitcraze/AIdeck_examples#24]
hello 
i have uploaded the face detection image on the ai deck, now i need to know how to run this code and receive images on the laptop. Could you explain how i can achieve this. Do i need to build an application to run on the laptop? 
thank you
regards
rodrigo calvo

**Comment by knmcguire** [comment]
If you make the face detection example with the define USE_STREAMER, then you should be able to stream the camera images to your computer. Just a warning though, the streamer does not work in SDK 3.6 or 3.7

Then check out the documentation for the wifistreamer: https://github.com/bitcraze/AIdeck_examples/blob/master/docs/test-functions/wifi-streamer.md

**Comment by knmcguire** [comment]
btw, we also have a AIdeck group on our forum: forum.bitcraze.io. That is a better location for questions that are not bug fixes or feature request.

**Comment by knmcguire** [comment]
I've added more info to the documentation so I will close this issue now
