### ISSUE TITLE
Where is the dockerfile for the Docker Nina?

### ISSUE THREAD

**Issue by RavenLite** [bitcraze/AIdeck_examples#27]
Hello, I see that you presented we could install the requirements and flash the nina using docker in the [Docker Nina](https://github.com/bitcraze/AIdeck_examples/blob/master/docs/nina-instructions/docker-nina.md). But I cannot find the dockerfile in this doc.

**Comment by knmcguire** [comment]
Its in the repo: AIdeck_examples/docker/nina/Dockerfile

**Comment by knmcguire** [comment]
I also added a comment in the documentation so it is a bit more clear :)

**Comment by RavenLite** [comment]
Thank you!
