### ISSUE TITLE
JPEG streammer as Client

### ISSUE THREAD

**Issue by Ozyman1998** [bitcraze/AIdeck_examples#59]
Hello!!!!
I have many crazyflie and I want to make them to stream images to my PC using my home wifi. My idea is to join the images using OpenCV in my computer, but for that I need the crazyflies to be wifi clients rather than servers. How can I do it??
The problem with the JPEG streamer in the examples is that I cannot receive images by openCV neither I know how to get several images at the same time. Any idea?

**Comment by knmcguire** [comment]
Hi! I saw that you have put the same question in the forum, so let's communicate further there: https://forum.bitcraze.io/viewtopic.php?p=23721#p23721
